"""date url rename

Revision ID: 27e2316fd9bf
Revises: de3178e43d97
Create Date: 2022-03-30 23:09:18.600685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e2316fd9bf'
down_revision = 'de3178e43d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('finish_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.drop_column('consultation_finish_time')
        batch_op.drop_column('consultation_start_time')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_parents_parent_id')
        batch_op.create_index(batch_op.f('ix_parents_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('fk_parents_parent_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_parents_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_parents_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_parents_parent_id_users', 'users', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_parents_user_id'))
        batch_op.create_index('ix_parents_parent_id', ['parent_id'], unique=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('consultation_finish_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('url')
        batch_op.drop_column('finish_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
