"""2

Revision ID: 8765892065d2
Revises: 50cc1d5fa698
Create Date: 2022-03-23 00:06:16.655671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8765892065d2'
down_revision = '50cc1d5fa698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_objects_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_objects_classes_class_id'), 'teacher_objects_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_objects_classes_id'), 'teacher_objects_classes', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_objects_classes_object_id'), 'teacher_objects_classes', ['object_id'], unique=False)
    op.create_index(op.f('ix_teacher_objects_classes_teacher_id'), 'teacher_objects_classes', ['teacher_id'], unique=False)
    op.drop_index('ix_teachers&objects&classes_class_id', table_name='teachers&objects&classes')
    op.drop_index('ix_teachers&objects&classes_id', table_name='teachers&objects&classes')
    op.drop_index('ix_teachers&objects&classes_object_id', table_name='teachers&objects&classes')
    op.drop_index('ix_teachers&objects&classes_teacher_id', table_name='teachers&objects&classes')
    op.drop_table('teachers&objects&classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers&objects&classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('object_id', sa.INTEGER(), nullable=True),
    sa.Column('class_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teachers&objects&classes_teacher_id', 'teachers&objects&classes', ['teacher_id'], unique=False)
    op.create_index('ix_teachers&objects&classes_object_id', 'teachers&objects&classes', ['object_id'], unique=False)
    op.create_index('ix_teachers&objects&classes_id', 'teachers&objects&classes', ['id'], unique=False)
    op.create_index('ix_teachers&objects&classes_class_id', 'teachers&objects&classes', ['class_id'], unique=False)
    op.drop_index(op.f('ix_teacher_objects_classes_teacher_id'), table_name='teacher_objects_classes')
    op.drop_index(op.f('ix_teacher_objects_classes_object_id'), table_name='teacher_objects_classes')
    op.drop_index(op.f('ix_teacher_objects_classes_id'), table_name='teacher_objects_classes')
    op.drop_index(op.f('ix_teacher_objects_classes_class_id'), table_name='teacher_objects_classes')
    op.drop_table('teacher_objects_classes')
    # ### end Alembic commands ###
