"""rename cons status

Revision ID: 89bfb8668071
Revises: daadde534c41
Create Date: 2022-04-17 16:39:12.640290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bfb8668071'
down_revision = 'daadde534c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('groups', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_classes_parallel'), ['parallel'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_free')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_classes_parallel'))
        batch_op.drop_column('groups')
        batch_op.drop_column('parallel')

    # ### end Alembic commands ###
