"""rename models

Revision ID: de3178e43d97
Revises: 8765892065d2
Create Date: 2022-03-27 21:31:21.249123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3178e43d97'
down_revision = '8765892065d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('teacher_subjects_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_subjects_classes_class_id'), 'teacher_subjects_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_classes_id'), 'teacher_subjects_classes', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_classes_subject_id'), 'teacher_subjects_classes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_classes_teacher_id'), 'teacher_subjects_classes', ['teacher_id'], unique=False)
    op.drop_index('ix_teacher_objects_classes_class_id', table_name='teacher_objects_classes')
    op.drop_index('ix_teacher_objects_classes_id', table_name='teacher_objects_classes')
    op.drop_index('ix_teacher_objects_classes_object_id', table_name='teacher_objects_classes')
    op.drop_index('ix_teacher_objects_classes_teacher_id', table_name='teacher_objects_classes')
    op.drop_table('teacher_objects_classes')
    op.drop_index('ix_objects_id', table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('about', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objects_id', 'objects', ['id'], unique=False)
    op.create_table('teacher_objects_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('object_id', sa.INTEGER(), nullable=True),
    sa.Column('class_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_objects_classes_teacher_id', 'teacher_objects_classes', ['teacher_id'], unique=False)
    op.create_index('ix_teacher_objects_classes_object_id', 'teacher_objects_classes', ['object_id'], unique=False)
    op.create_index('ix_teacher_objects_classes_id', 'teacher_objects_classes', ['id'], unique=False)
    op.create_index('ix_teacher_objects_classes_class_id', 'teacher_objects_classes', ['class_id'], unique=False)
    op.drop_index(op.f('ix_teacher_subjects_classes_teacher_id'), table_name='teacher_subjects_classes')
    op.drop_index(op.f('ix_teacher_subjects_classes_subject_id'), table_name='teacher_subjects_classes')
    op.drop_index(op.f('ix_teacher_subjects_classes_id'), table_name='teacher_subjects_classes')
    op.drop_index(op.f('ix_teacher_subjects_classes_class_id'), table_name='teacher_subjects_classes')
    op.drop_table('teacher_subjects_classes')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
