"""Initial migration

Revision ID: fecd6f12bbde
Revises: 
Create Date: 2022-03-09 21:45:08.584418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecd6f12bbde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_hashed_password'), 'admins', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_school_id'), 'admins', ['school_id'], unique=False)
    op.create_index(op.f('ix_admins_surname'), 'admins', ['surname'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_class_id'), 'parents', ['class_id'], unique=False)
    op.create_index(op.f('ix_parents_hashed_password'), 'parents', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_login'), 'parents', ['login'], unique=True)
    op.create_index(op.f('ix_parents_school_id'), 'parents', ['school_id'], unique=False)
    op.create_index(op.f('ix_parents_surname'), 'parents', ['surname'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_hashed_password'), 'teachers', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_login'), 'teachers', ['login'], unique=True)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_teachers_surname'), 'teachers', ['surname'], unique=False)
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_id'), 'consultation', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_parent_id'), 'consultation', ['parent_id'], unique=False)
    op.create_index(op.f('ix_consultation_teacher_id'), 'consultation', ['teacher_id'], unique=False)
    op.create_table('teachers_and_classes_and_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_and_classes_and_objects_class_id'), 'teachers_and_classes_and_objects', ['class_id'], unique=False)
    op.create_index(op.f('ix_teachers_and_classes_and_objects_id'), 'teachers_and_classes_and_objects', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_and_classes_and_objects_object_id'), 'teachers_and_classes_and_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_teachers_and_classes_and_objects_teacher_id'), 'teachers_and_classes_and_objects', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_and_classes_and_objects_teacher_id'), table_name='teachers_and_classes_and_objects')
    op.drop_index(op.f('ix_teachers_and_classes_and_objects_object_id'), table_name='teachers_and_classes_and_objects')
    op.drop_index(op.f('ix_teachers_and_classes_and_objects_id'), table_name='teachers_and_classes_and_objects')
    op.drop_index(op.f('ix_teachers_and_classes_and_objects_class_id'), table_name='teachers_and_classes_and_objects')
    op.drop_table('teachers_and_classes_and_objects')
    op.drop_index(op.f('ix_consultation_teacher_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_parent_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_id'), table_name='consultation')
    op.drop_table('consultation')
    op.drop_index(op.f('ix_teachers_surname'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_login'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_hashed_password'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_parents_surname'), table_name='parents')
    op.drop_index(op.f('ix_parents_school_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_login'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_hashed_password'), table_name='parents')
    op.drop_index(op.f('ix_parents_class_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_admins_surname'), table_name='admins')
    op.drop_index(op.f('ix_admins_school_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_hashed_password'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
